// Generated code, see gencode.rb

BOOL __attribute__((overloadable)) (^ITBUnbox(BOOL (^block)(BOOL unboxed)))(id);
BOOL __attribute__((overloadable)) (^ITBUnbox(BOOL (^block)(char unboxed)))(id);
BOOL __attribute__((overloadable)) (^ITBUnbox(BOOL (^block)(unsigned char unboxed)))(id);
BOOL __attribute__((overloadable)) (^ITBUnbox(BOOL (^block)(short unboxed)))(id);
BOOL __attribute__((overloadable)) (^ITBUnbox(BOOL (^block)(unsigned short unboxed)))(id);
BOOL __attribute__((overloadable)) (^ITBUnbox(BOOL (^block)(int unboxed)))(id);
BOOL __attribute__((overloadable)) (^ITBUnbox(BOOL (^block)(unsigned int unboxed)))(id);
BOOL __attribute__((overloadable)) (^ITBUnbox(BOOL (^block)(long unboxed)))(id);
BOOL __attribute__((overloadable)) (^ITBUnbox(BOOL (^block)(unsigned long unboxed)))(id);
BOOL __attribute__((overloadable)) (^ITBUnbox(BOOL (^block)(long long unboxed)))(id);
BOOL __attribute__((overloadable)) (^ITBUnbox(BOOL (^block)(unsigned long long unboxed)))(id);
BOOL __attribute__((overloadable)) (^ITBUnbox(BOOL (^block)(float unboxed)))(id);
BOOL __attribute__((overloadable)) (^ITBUnbox(BOOL (^block)(double unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(BOOL (^block)(BOOL unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(BOOL (^block)(char unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(BOOL (^block)(unsigned char unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(BOOL (^block)(short unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(BOOL (^block)(unsigned short unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(BOOL (^block)(int unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(BOOL (^block)(unsigned int unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(BOOL (^block)(long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(BOOL (^block)(unsigned long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(BOOL (^block)(long long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(BOOL (^block)(unsigned long long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(BOOL (^block)(float unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(BOOL (^block)(double unboxed)))(id);

char __attribute__((overloadable)) (^ITBUnbox(char (^block)(BOOL unboxed)))(id);
char __attribute__((overloadable)) (^ITBUnbox(char (^block)(char unboxed)))(id);
char __attribute__((overloadable)) (^ITBUnbox(char (^block)(unsigned char unboxed)))(id);
char __attribute__((overloadable)) (^ITBUnbox(char (^block)(short unboxed)))(id);
char __attribute__((overloadable)) (^ITBUnbox(char (^block)(unsigned short unboxed)))(id);
char __attribute__((overloadable)) (^ITBUnbox(char (^block)(int unboxed)))(id);
char __attribute__((overloadable)) (^ITBUnbox(char (^block)(unsigned int unboxed)))(id);
char __attribute__((overloadable)) (^ITBUnbox(char (^block)(long unboxed)))(id);
char __attribute__((overloadable)) (^ITBUnbox(char (^block)(unsigned long unboxed)))(id);
char __attribute__((overloadable)) (^ITBUnbox(char (^block)(long long unboxed)))(id);
char __attribute__((overloadable)) (^ITBUnbox(char (^block)(unsigned long long unboxed)))(id);
char __attribute__((overloadable)) (^ITBUnbox(char (^block)(float unboxed)))(id);
char __attribute__((overloadable)) (^ITBUnbox(char (^block)(double unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(char (^block)(BOOL unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(char (^block)(char unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(char (^block)(unsigned char unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(char (^block)(short unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(char (^block)(unsigned short unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(char (^block)(int unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(char (^block)(unsigned int unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(char (^block)(long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(char (^block)(unsigned long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(char (^block)(long long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(char (^block)(unsigned long long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(char (^block)(float unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(char (^block)(double unboxed)))(id);

unsigned char __attribute__((overloadable)) (^ITBUnbox(unsigned char (^block)(BOOL unboxed)))(id);
unsigned char __attribute__((overloadable)) (^ITBUnbox(unsigned char (^block)(char unboxed)))(id);
unsigned char __attribute__((overloadable)) (^ITBUnbox(unsigned char (^block)(unsigned char unboxed)))(id);
unsigned char __attribute__((overloadable)) (^ITBUnbox(unsigned char (^block)(short unboxed)))(id);
unsigned char __attribute__((overloadable)) (^ITBUnbox(unsigned char (^block)(unsigned short unboxed)))(id);
unsigned char __attribute__((overloadable)) (^ITBUnbox(unsigned char (^block)(int unboxed)))(id);
unsigned char __attribute__((overloadable)) (^ITBUnbox(unsigned char (^block)(unsigned int unboxed)))(id);
unsigned char __attribute__((overloadable)) (^ITBUnbox(unsigned char (^block)(long unboxed)))(id);
unsigned char __attribute__((overloadable)) (^ITBUnbox(unsigned char (^block)(unsigned long unboxed)))(id);
unsigned char __attribute__((overloadable)) (^ITBUnbox(unsigned char (^block)(long long unboxed)))(id);
unsigned char __attribute__((overloadable)) (^ITBUnbox(unsigned char (^block)(unsigned long long unboxed)))(id);
unsigned char __attribute__((overloadable)) (^ITBUnbox(unsigned char (^block)(float unboxed)))(id);
unsigned char __attribute__((overloadable)) (^ITBUnbox(unsigned char (^block)(double unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned char (^block)(BOOL unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned char (^block)(char unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned char (^block)(unsigned char unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned char (^block)(short unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned char (^block)(unsigned short unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned char (^block)(int unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned char (^block)(unsigned int unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned char (^block)(long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned char (^block)(unsigned long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned char (^block)(long long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned char (^block)(unsigned long long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned char (^block)(float unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned char (^block)(double unboxed)))(id);

short __attribute__((overloadable)) (^ITBUnbox(short (^block)(BOOL unboxed)))(id);
short __attribute__((overloadable)) (^ITBUnbox(short (^block)(char unboxed)))(id);
short __attribute__((overloadable)) (^ITBUnbox(short (^block)(unsigned char unboxed)))(id);
short __attribute__((overloadable)) (^ITBUnbox(short (^block)(short unboxed)))(id);
short __attribute__((overloadable)) (^ITBUnbox(short (^block)(unsigned short unboxed)))(id);
short __attribute__((overloadable)) (^ITBUnbox(short (^block)(int unboxed)))(id);
short __attribute__((overloadable)) (^ITBUnbox(short (^block)(unsigned int unboxed)))(id);
short __attribute__((overloadable)) (^ITBUnbox(short (^block)(long unboxed)))(id);
short __attribute__((overloadable)) (^ITBUnbox(short (^block)(unsigned long unboxed)))(id);
short __attribute__((overloadable)) (^ITBUnbox(short (^block)(long long unboxed)))(id);
short __attribute__((overloadable)) (^ITBUnbox(short (^block)(unsigned long long unboxed)))(id);
short __attribute__((overloadable)) (^ITBUnbox(short (^block)(float unboxed)))(id);
short __attribute__((overloadable)) (^ITBUnbox(short (^block)(double unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(short (^block)(BOOL unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(short (^block)(char unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(short (^block)(unsigned char unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(short (^block)(short unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(short (^block)(unsigned short unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(short (^block)(int unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(short (^block)(unsigned int unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(short (^block)(long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(short (^block)(unsigned long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(short (^block)(long long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(short (^block)(unsigned long long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(short (^block)(float unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(short (^block)(double unboxed)))(id);

unsigned short __attribute__((overloadable)) (^ITBUnbox(unsigned short (^block)(BOOL unboxed)))(id);
unsigned short __attribute__((overloadable)) (^ITBUnbox(unsigned short (^block)(char unboxed)))(id);
unsigned short __attribute__((overloadable)) (^ITBUnbox(unsigned short (^block)(unsigned char unboxed)))(id);
unsigned short __attribute__((overloadable)) (^ITBUnbox(unsigned short (^block)(short unboxed)))(id);
unsigned short __attribute__((overloadable)) (^ITBUnbox(unsigned short (^block)(unsigned short unboxed)))(id);
unsigned short __attribute__((overloadable)) (^ITBUnbox(unsigned short (^block)(int unboxed)))(id);
unsigned short __attribute__((overloadable)) (^ITBUnbox(unsigned short (^block)(unsigned int unboxed)))(id);
unsigned short __attribute__((overloadable)) (^ITBUnbox(unsigned short (^block)(long unboxed)))(id);
unsigned short __attribute__((overloadable)) (^ITBUnbox(unsigned short (^block)(unsigned long unboxed)))(id);
unsigned short __attribute__((overloadable)) (^ITBUnbox(unsigned short (^block)(long long unboxed)))(id);
unsigned short __attribute__((overloadable)) (^ITBUnbox(unsigned short (^block)(unsigned long long unboxed)))(id);
unsigned short __attribute__((overloadable)) (^ITBUnbox(unsigned short (^block)(float unboxed)))(id);
unsigned short __attribute__((overloadable)) (^ITBUnbox(unsigned short (^block)(double unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned short (^block)(BOOL unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned short (^block)(char unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned short (^block)(unsigned char unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned short (^block)(short unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned short (^block)(unsigned short unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned short (^block)(int unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned short (^block)(unsigned int unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned short (^block)(long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned short (^block)(unsigned long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned short (^block)(long long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned short (^block)(unsigned long long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned short (^block)(float unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned short (^block)(double unboxed)))(id);

int __attribute__((overloadable)) (^ITBUnbox(int (^block)(BOOL unboxed)))(id);
int __attribute__((overloadable)) (^ITBUnbox(int (^block)(char unboxed)))(id);
int __attribute__((overloadable)) (^ITBUnbox(int (^block)(unsigned char unboxed)))(id);
int __attribute__((overloadable)) (^ITBUnbox(int (^block)(short unboxed)))(id);
int __attribute__((overloadable)) (^ITBUnbox(int (^block)(unsigned short unboxed)))(id);
int __attribute__((overloadable)) (^ITBUnbox(int (^block)(int unboxed)))(id);
int __attribute__((overloadable)) (^ITBUnbox(int (^block)(unsigned int unboxed)))(id);
int __attribute__((overloadable)) (^ITBUnbox(int (^block)(long unboxed)))(id);
int __attribute__((overloadable)) (^ITBUnbox(int (^block)(unsigned long unboxed)))(id);
int __attribute__((overloadable)) (^ITBUnbox(int (^block)(long long unboxed)))(id);
int __attribute__((overloadable)) (^ITBUnbox(int (^block)(unsigned long long unboxed)))(id);
int __attribute__((overloadable)) (^ITBUnbox(int (^block)(float unboxed)))(id);
int __attribute__((overloadable)) (^ITBUnbox(int (^block)(double unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(int (^block)(BOOL unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(int (^block)(char unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(int (^block)(unsigned char unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(int (^block)(short unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(int (^block)(unsigned short unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(int (^block)(int unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(int (^block)(unsigned int unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(int (^block)(long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(int (^block)(unsigned long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(int (^block)(long long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(int (^block)(unsigned long long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(int (^block)(float unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(int (^block)(double unboxed)))(id);

unsigned int __attribute__((overloadable)) (^ITBUnbox(unsigned int (^block)(BOOL unboxed)))(id);
unsigned int __attribute__((overloadable)) (^ITBUnbox(unsigned int (^block)(char unboxed)))(id);
unsigned int __attribute__((overloadable)) (^ITBUnbox(unsigned int (^block)(unsigned char unboxed)))(id);
unsigned int __attribute__((overloadable)) (^ITBUnbox(unsigned int (^block)(short unboxed)))(id);
unsigned int __attribute__((overloadable)) (^ITBUnbox(unsigned int (^block)(unsigned short unboxed)))(id);
unsigned int __attribute__((overloadable)) (^ITBUnbox(unsigned int (^block)(int unboxed)))(id);
unsigned int __attribute__((overloadable)) (^ITBUnbox(unsigned int (^block)(unsigned int unboxed)))(id);
unsigned int __attribute__((overloadable)) (^ITBUnbox(unsigned int (^block)(long unboxed)))(id);
unsigned int __attribute__((overloadable)) (^ITBUnbox(unsigned int (^block)(unsigned long unboxed)))(id);
unsigned int __attribute__((overloadable)) (^ITBUnbox(unsigned int (^block)(long long unboxed)))(id);
unsigned int __attribute__((overloadable)) (^ITBUnbox(unsigned int (^block)(unsigned long long unboxed)))(id);
unsigned int __attribute__((overloadable)) (^ITBUnbox(unsigned int (^block)(float unboxed)))(id);
unsigned int __attribute__((overloadable)) (^ITBUnbox(unsigned int (^block)(double unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned int (^block)(BOOL unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned int (^block)(char unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned int (^block)(unsigned char unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned int (^block)(short unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned int (^block)(unsigned short unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned int (^block)(int unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned int (^block)(unsigned int unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned int (^block)(long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned int (^block)(unsigned long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned int (^block)(long long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned int (^block)(unsigned long long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned int (^block)(float unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned int (^block)(double unboxed)))(id);

long __attribute__((overloadable)) (^ITBUnbox(long (^block)(BOOL unboxed)))(id);
long __attribute__((overloadable)) (^ITBUnbox(long (^block)(char unboxed)))(id);
long __attribute__((overloadable)) (^ITBUnbox(long (^block)(unsigned char unboxed)))(id);
long __attribute__((overloadable)) (^ITBUnbox(long (^block)(short unboxed)))(id);
long __attribute__((overloadable)) (^ITBUnbox(long (^block)(unsigned short unboxed)))(id);
long __attribute__((overloadable)) (^ITBUnbox(long (^block)(int unboxed)))(id);
long __attribute__((overloadable)) (^ITBUnbox(long (^block)(unsigned int unboxed)))(id);
long __attribute__((overloadable)) (^ITBUnbox(long (^block)(long unboxed)))(id);
long __attribute__((overloadable)) (^ITBUnbox(long (^block)(unsigned long unboxed)))(id);
long __attribute__((overloadable)) (^ITBUnbox(long (^block)(long long unboxed)))(id);
long __attribute__((overloadable)) (^ITBUnbox(long (^block)(unsigned long long unboxed)))(id);
long __attribute__((overloadable)) (^ITBUnbox(long (^block)(float unboxed)))(id);
long __attribute__((overloadable)) (^ITBUnbox(long (^block)(double unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(long (^block)(BOOL unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(long (^block)(char unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(long (^block)(unsigned char unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(long (^block)(short unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(long (^block)(unsigned short unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(long (^block)(int unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(long (^block)(unsigned int unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(long (^block)(long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(long (^block)(unsigned long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(long (^block)(long long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(long (^block)(unsigned long long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(long (^block)(float unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(long (^block)(double unboxed)))(id);

unsigned long __attribute__((overloadable)) (^ITBUnbox(unsigned long (^block)(BOOL unboxed)))(id);
unsigned long __attribute__((overloadable)) (^ITBUnbox(unsigned long (^block)(char unboxed)))(id);
unsigned long __attribute__((overloadable)) (^ITBUnbox(unsigned long (^block)(unsigned char unboxed)))(id);
unsigned long __attribute__((overloadable)) (^ITBUnbox(unsigned long (^block)(short unboxed)))(id);
unsigned long __attribute__((overloadable)) (^ITBUnbox(unsigned long (^block)(unsigned short unboxed)))(id);
unsigned long __attribute__((overloadable)) (^ITBUnbox(unsigned long (^block)(int unboxed)))(id);
unsigned long __attribute__((overloadable)) (^ITBUnbox(unsigned long (^block)(unsigned int unboxed)))(id);
unsigned long __attribute__((overloadable)) (^ITBUnbox(unsigned long (^block)(long unboxed)))(id);
unsigned long __attribute__((overloadable)) (^ITBUnbox(unsigned long (^block)(unsigned long unboxed)))(id);
unsigned long __attribute__((overloadable)) (^ITBUnbox(unsigned long (^block)(long long unboxed)))(id);
unsigned long __attribute__((overloadable)) (^ITBUnbox(unsigned long (^block)(unsigned long long unboxed)))(id);
unsigned long __attribute__((overloadable)) (^ITBUnbox(unsigned long (^block)(float unboxed)))(id);
unsigned long __attribute__((overloadable)) (^ITBUnbox(unsigned long (^block)(double unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned long (^block)(BOOL unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned long (^block)(char unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned long (^block)(unsigned char unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned long (^block)(short unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned long (^block)(unsigned short unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned long (^block)(int unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned long (^block)(unsigned int unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned long (^block)(long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned long (^block)(unsigned long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned long (^block)(long long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned long (^block)(unsigned long long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned long (^block)(float unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned long (^block)(double unboxed)))(id);

long long __attribute__((overloadable)) (^ITBUnbox(long long (^block)(BOOL unboxed)))(id);
long long __attribute__((overloadable)) (^ITBUnbox(long long (^block)(char unboxed)))(id);
long long __attribute__((overloadable)) (^ITBUnbox(long long (^block)(unsigned char unboxed)))(id);
long long __attribute__((overloadable)) (^ITBUnbox(long long (^block)(short unboxed)))(id);
long long __attribute__((overloadable)) (^ITBUnbox(long long (^block)(unsigned short unboxed)))(id);
long long __attribute__((overloadable)) (^ITBUnbox(long long (^block)(int unboxed)))(id);
long long __attribute__((overloadable)) (^ITBUnbox(long long (^block)(unsigned int unboxed)))(id);
long long __attribute__((overloadable)) (^ITBUnbox(long long (^block)(long unboxed)))(id);
long long __attribute__((overloadable)) (^ITBUnbox(long long (^block)(unsigned long unboxed)))(id);
long long __attribute__((overloadable)) (^ITBUnbox(long long (^block)(long long unboxed)))(id);
long long __attribute__((overloadable)) (^ITBUnbox(long long (^block)(unsigned long long unboxed)))(id);
long long __attribute__((overloadable)) (^ITBUnbox(long long (^block)(float unboxed)))(id);
long long __attribute__((overloadable)) (^ITBUnbox(long long (^block)(double unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(long long (^block)(BOOL unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(long long (^block)(char unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(long long (^block)(unsigned char unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(long long (^block)(short unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(long long (^block)(unsigned short unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(long long (^block)(int unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(long long (^block)(unsigned int unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(long long (^block)(long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(long long (^block)(unsigned long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(long long (^block)(long long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(long long (^block)(unsigned long long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(long long (^block)(float unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(long long (^block)(double unboxed)))(id);

unsigned long long __attribute__((overloadable)) (^ITBUnbox(unsigned long long (^block)(BOOL unboxed)))(id);
unsigned long long __attribute__((overloadable)) (^ITBUnbox(unsigned long long (^block)(char unboxed)))(id);
unsigned long long __attribute__((overloadable)) (^ITBUnbox(unsigned long long (^block)(unsigned char unboxed)))(id);
unsigned long long __attribute__((overloadable)) (^ITBUnbox(unsigned long long (^block)(short unboxed)))(id);
unsigned long long __attribute__((overloadable)) (^ITBUnbox(unsigned long long (^block)(unsigned short unboxed)))(id);
unsigned long long __attribute__((overloadable)) (^ITBUnbox(unsigned long long (^block)(int unboxed)))(id);
unsigned long long __attribute__((overloadable)) (^ITBUnbox(unsigned long long (^block)(unsigned int unboxed)))(id);
unsigned long long __attribute__((overloadable)) (^ITBUnbox(unsigned long long (^block)(long unboxed)))(id);
unsigned long long __attribute__((overloadable)) (^ITBUnbox(unsigned long long (^block)(unsigned long unboxed)))(id);
unsigned long long __attribute__((overloadable)) (^ITBUnbox(unsigned long long (^block)(long long unboxed)))(id);
unsigned long long __attribute__((overloadable)) (^ITBUnbox(unsigned long long (^block)(unsigned long long unboxed)))(id);
unsigned long long __attribute__((overloadable)) (^ITBUnbox(unsigned long long (^block)(float unboxed)))(id);
unsigned long long __attribute__((overloadable)) (^ITBUnbox(unsigned long long (^block)(double unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned long long (^block)(BOOL unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned long long (^block)(char unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned long long (^block)(unsigned char unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned long long (^block)(short unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned long long (^block)(unsigned short unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned long long (^block)(int unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned long long (^block)(unsigned int unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned long long (^block)(long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned long long (^block)(unsigned long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned long long (^block)(long long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned long long (^block)(unsigned long long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned long long (^block)(float unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(unsigned long long (^block)(double unboxed)))(id);

float __attribute__((overloadable)) (^ITBUnbox(float (^block)(BOOL unboxed)))(id);
float __attribute__((overloadable)) (^ITBUnbox(float (^block)(char unboxed)))(id);
float __attribute__((overloadable)) (^ITBUnbox(float (^block)(unsigned char unboxed)))(id);
float __attribute__((overloadable)) (^ITBUnbox(float (^block)(short unboxed)))(id);
float __attribute__((overloadable)) (^ITBUnbox(float (^block)(unsigned short unboxed)))(id);
float __attribute__((overloadable)) (^ITBUnbox(float (^block)(int unboxed)))(id);
float __attribute__((overloadable)) (^ITBUnbox(float (^block)(unsigned int unboxed)))(id);
float __attribute__((overloadable)) (^ITBUnbox(float (^block)(long unboxed)))(id);
float __attribute__((overloadable)) (^ITBUnbox(float (^block)(unsigned long unboxed)))(id);
float __attribute__((overloadable)) (^ITBUnbox(float (^block)(long long unboxed)))(id);
float __attribute__((overloadable)) (^ITBUnbox(float (^block)(unsigned long long unboxed)))(id);
float __attribute__((overloadable)) (^ITBUnbox(float (^block)(float unboxed)))(id);
float __attribute__((overloadable)) (^ITBUnbox(float (^block)(double unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(float (^block)(BOOL unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(float (^block)(char unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(float (^block)(unsigned char unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(float (^block)(short unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(float (^block)(unsigned short unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(float (^block)(int unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(float (^block)(unsigned int unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(float (^block)(long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(float (^block)(unsigned long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(float (^block)(long long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(float (^block)(unsigned long long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(float (^block)(float unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(float (^block)(double unboxed)))(id);

double __attribute__((overloadable)) (^ITBUnbox(double (^block)(BOOL unboxed)))(id);
double __attribute__((overloadable)) (^ITBUnbox(double (^block)(char unboxed)))(id);
double __attribute__((overloadable)) (^ITBUnbox(double (^block)(unsigned char unboxed)))(id);
double __attribute__((overloadable)) (^ITBUnbox(double (^block)(short unboxed)))(id);
double __attribute__((overloadable)) (^ITBUnbox(double (^block)(unsigned short unboxed)))(id);
double __attribute__((overloadable)) (^ITBUnbox(double (^block)(int unboxed)))(id);
double __attribute__((overloadable)) (^ITBUnbox(double (^block)(unsigned int unboxed)))(id);
double __attribute__((overloadable)) (^ITBUnbox(double (^block)(long unboxed)))(id);
double __attribute__((overloadable)) (^ITBUnbox(double (^block)(unsigned long unboxed)))(id);
double __attribute__((overloadable)) (^ITBUnbox(double (^block)(long long unboxed)))(id);
double __attribute__((overloadable)) (^ITBUnbox(double (^block)(unsigned long long unboxed)))(id);
double __attribute__((overloadable)) (^ITBUnbox(double (^block)(float unboxed)))(id);
double __attribute__((overloadable)) (^ITBUnbox(double (^block)(double unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(double (^block)(BOOL unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(double (^block)(char unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(double (^block)(unsigned char unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(double (^block)(short unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(double (^block)(unsigned short unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(double (^block)(int unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(double (^block)(unsigned int unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(double (^block)(long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(double (^block)(unsigned long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(double (^block)(long long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(double (^block)(unsigned long long unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(double (^block)(float unboxed)))(id);
id __attribute__((overloadable)) (^ITBRebox(double (^block)(double unboxed)))(id);

